site_name: pydevcli Docs

theme:
  name: material
  palette:
    - scheme: 
      primary: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: README.md
  - Installation: installation.md
  - Development: development.md
  - Changelog: CHANGELOG.md
