site_name: pydevcli Docs

theme:
  name: material
  palette:
    - scheme: 
      primary: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode